### ISSUE TITLE
2.28.0 assets are not showing in cdnjs

### ISSUE THREAD

**Issue by tekoyaki** [Alex-D/Trumbowyg#1471]
I cannot see the files for 2.28.0, other versions are fine. Unsure if this is cdnjs bug or just not yet uploaded: https://cdnjs.com/libraries/Trumbowyg

**Comment by Alex-D** [comment]
Fixed with the 2.29.0 and 2.30.0 versions :)

**Comment by tekoyaki** [comment]
It's been 2 weeks and they still don't show up: https://cdnjs.com/libraries/Trumbowyg

I'm also not seeing 2.29 and 2.30 there, so I switched to jsdelivr.
