### ISSUE TITLE
IE8 only works with min.js

### ISSUE THREAD

**Issue by andyburton** [Alex-D/Trumbowyg#201]
IE8 doesn't work with trumbowyg.js but it does with the min.js version.

This is because trumbowyg.js does not have quotes around the reserved object keys (e.g. {class: 'className'} when creating elements) and breaks IE. The minified version does have quotes and thus works correctly (e.g. {"class": 'className'}).

As you can imagine it was VERY confusing to work out why Trumbowyg stopped working in my app without any changes whatsoever, besides the gulp script being inconspicuously changed :sob:

**Comment by andyburton** [comment]
Ah... this looks to already be fixed in the v2 beta. I was using the 1.1.7 stable.

**Comment by Alex-D** [comment]
Yep, I need to stabilize v2 and publish them on bower.

**Comment by jburagev** [comment]
I still see the issue here in IE11. I get error "Expected identifier, string or number" on line 287 in trumbowyg.js where class: is defined and i guess this error appears because class is reserved word in JavaScript IE.

 It is not working with trumbowyg.min.js as well, but here gives some other error >>Object doesn't support property or method 'defineProperty'<<. 

Is there some fix around this or i am doing something wrong? Thanks in advance!

**Comment by moorthidaniel** [comment]
I am still facing this issue with IE 11 compatibility mode enabled.
SCRIPT438: Object doesn't support property or method 'defineProperty'
trumbowyg.min.js (2,873)
SCRIPT438: Object doesn't support property or method 'trumbowyg'
35c91c5c043b16bc072585450037546a (2328,7)
