### ISSUE TITLE
Disable non-breaking space

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#240]
Two users report headache with the non-breaking space character support. After copy pasting text they need to strip out nbsp characters manually.

A boolean config param wheither or not nbsp is allowed to be produced would be great.

**Comment by Alex-D** [comment]
Have you try the [remove format pasted](http://alex-d.github.io/Trumbowyg/documentation.html#remove-format-pasted) option?

**Comment by timint** [comment]
That's a must have setting, yes it's enabled. :)

**Comment by Alex-D** [comment]
And it's do the job?

**Comment by timint** [comment]
No, I'm gonna see if it's any different in the latest version.

**Comment by timint** [comment]
It seems like the problem is solved in the latest version beta 8. There is no track of multiple nbsp chars. when copy pasting text. The hard spaces seem to be swept away replaced by soft spacings.

**Comment by Alex-D** [comment]
Cool :)

**Comment by bentito** [comment]
So it there a setting to eliminate the soft space additions too? I tried the "remove format pasted" option, but it still seems to want to add spaces. They are at least \x20's now, but still not desired. To my mind they go against WYSIWYG since I "See" no spaces in my copy/cut element, but I "Get" spaces in my paste element.

**Comment by Alex-D** [comment]
Idk. I don't understand what do you meen by "soft space" :/

**Comment by bentito** [comment]
Well with an older version of Trumbowyg I was seeing the \xC2A0 (no break space) being added on either side of the paste. I was glad that in the latest version that seems to have been replaced by a simple \x20 (soft space? idk, let's just refer in hex and save the semantic problems) on either side of the paste. That's better, at least the user can see the spaces and deal with them as spaces if needed. But I don't think they belong there at all. They are not in the cut/copy element, so why add them for the user on the paste?

**Comment by bentito** [comment]
BTW, a little more playing around shows me that when I copy text from between non-whitespace (like fooFOOfoo if I select just the FOO), I do not get the spaces added on paste. When I copy a word with whitespace on either side (like fii FOO faa, copying just the FOO) I see my selection does not include the whitespaces, but my paste does. So the behavior is different based on where my cut/copy element came from, that seems hard to deal with as a user.

**Comment by Alex-D** [comment]
Your problem is a new problem that should have it's own issue with details on Trumbowyg version, configuration used, browser version, os version, etc.

I can't debug without a test case.

**Comment by bentito** [comment]
ah okay, I'll get that and start a new issue.
