### ISSUE TITLE
Can't "turn off" <del>

### ISSUE THREAD

**Issue by linux-man** [Alex-D/Trumbowyg#293]
It seems that it's the only tag where this happens (strong, italic, etc, work fine).

**Comment by linux-man** [comment]
...but with semantic: false, "stroke" can be disabled.

**Comment by istrau3** [comment]
+1, same issue.

**Comment by istrau3** [comment]
I wanted to add that superscript and subscript cannot be removed either (except by using undo).

**Comment by Alex-D** [comment]
I think this bug come from content editable :/

**Comment by Alex-D** [comment]
Fixed in 7cadf9d

**Comment by katafrakt** [comment]
I'm afraid it is still present. Just took this with master code. Strikethrough can be turned off (although at the first time it creates new paragraph). But subscript and superscript - still cannot (although video does not show my compulsive mouse clicking on them).

![](https://cloud.githubusercontent.com/assets/119904/17537419/c9264ab0-5e9c-11e6-82cb-1854f0820f61.gif)

**Comment by Alex-D** [comment]
OK. I've tested. It works. This bug is another bug due to empty editor at start.
So, I need to fix this another bug but this one is OK now :)

**Comment by blocknotes** [comment]
Hi @Alex-D 
I have the same problem... "Deleted", "Superscript" (in Chrome) and "Subscript" (in Chrome) can't be set off. And I see the same behavior also in your [demo](https://alex-d.github.io/Trumbowyg/) page

**Comment by Alex-D** [comment]
You right, but I can't fix more that since it seems to be a browser-level bug :/
